[project]
name = "parallel-sidechain-container"
authors = ["Web3 Infrastructure Team"]
description = "A decentralized framework for cross-chain sidechain registration and management"
telemetry = false
requirements = []

[contracts.sidechain-registry]
path = "contracts/sidechain-registry.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = true
